name: kemasindo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  awesome_dialog: ^3.0.2
  cupertino_icons: ^1.0.2
  fl_chart: ^0.55.2
  floating_bottom_navigation_bar: ^1.5.2
  flutter:
    sdk: flutter
  geolocation: ^9.0.2
  get: 4.6.5
  get_storage: ^2.0.3
  google_maps_flutter: ^2.2.1
  intl: ^0.17.0
  lottie: ^1.3.0
  maps_toolkit: ^2.0.1
  package_info_plus: ^3.0.2
  responsive_builder: ^0.4.3
  table_calendar: ^3.0.8
  timelines: ^0.1.0
  dropdown_button2: ^1.2.2
  image_picker: ^0.8.6


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/png/

  fonts:
    - family: Digital
      fonts:
        - asset: assets/fonts/Digital.otf
    - family: TickingTimebombBB
      fonts:
        - asset: assets/fonts/TickingTimebombBB.ttf
